Repository perun-network/perun-eth-demo, pull requests merged in 2020-07, with the labels that each got.

#12 [node] Fixed logger initialisation in peer
  cmd/demo/node.go
Labels: bug

#14 :pencil: [readme] revise walkthrough
  README.md
Labels: bug, documentation

#17 :lock: validate contracts instantiated from network address
  README.md
  alice.yaml
  bob.yaml
  cmd/demo/node_setup.go
  network.yaml
Labels: enhancement

#16 :bug:, :recycle: [cmd, demo] fix error on cmd help
  cmd/demo/config.go
  cmd/demo/demo.go
  cmd/demo/demo_test.go
  cmd/root.go
Labels: bug
